servlet:
  multipart:
    enabled: true
    location: d:/temp/pic
    file-size-threshold: 5MB
    max-file-size: 20MB

qiniu:
  accessKey: e68GRobk3q3O7HzqHWV6RpNh8f7ZG_-7iyM2FaTA
  secretKey: KDBqTVEvDiASX_Xh0WT_ck3hyZ2swu5HVh8TE7-_
  bucket: testupload3
  domain: r6ctg8uno.hd-bkt.clouddn.com
  expireSeconds: 1800