spring:
  data:
    redis:
      repositories:
        enabled: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:

  mail:
    email: yuanbaotest2022@163.com
    host: smtp.163.com
    port: 465
    username: yuanbaotest2022
    # 授权密码， 非邮箱密码，授权码是用于登录第三方邮件客户端的专用密码。
    password: DHUXCMZOLIBXDIHW

servlet:
  multipart:
    enabled: true
    location: d:/temp/pic
    file-size-threshold: 5MB
    max-file-size: 20MB

qiniu:
  accessKey: e68GRobk3q3O7HzqHWV6RpNh8f7ZG_-7iyM2FaTA
  secretKey: KDBqTVEvDiASX_Xh0WT_ck3hyZ2swu5HVh8TE7-_
  bucket: testupload3
  domain: r6ctg8uno.hd-bkt.clouddn.com
  expireSeconds: 1800