server:
  port: 8082

spring:
  profiles:
    active: common,mbp
  aop:
    proxy-target-class: true

## 显示dao 执⾏sql语句
logging:
  level:
    com.yuanbao.record.mbp.mapper: debug # 改成你的dao接口文件所在包路径可以打印出sql语句
